export const COUNTIES = [
  'Buckinghamshire',
  // 'Cambridgeshire',
  // 'Cumbria',
  // 'Derbyshire',
  // 'Devon',
  // 'Dorset',
  // 'East Sussex',
  // 'Essex',
  // 'Gloucestershire',
  // 'Hampshire',
  // 'Hertfordshire',
  // 'Kent',
  // 'Lancashire',
  // 'Leicestershire',
  // 'Lincolnshire',
  // 'Norfolk',
  // 'Northamptonshire',
  // 'North Yorkshire',
  // 'Nottinghamshire',
  // 'Oxfordshire',
  // 'Somerset',
  // 'Staffordshire',
  // 'Suffolk',
  // 'Surrey',
  // 'Warwickshire',
  // 'West Sussex',
  // 'Worcestershire',
  // 'Greater London',
  // 'South Yorkshire',
  // 'West Midlands',
  // 'Greater Manchester',
  // 'West Yorkshire',
  // 'Tyne and Wear',
  // 'Merseyside',
  // 'Bedfordshire',
  // 'Berkshire',
  // 'Cheshire',
  // 'Bristol',
  // 'East Riding of Yorkshire',
  // 'Cornwall',
  // 'County Durham',
  // 'Herefordshire',
  // 'Isle of Wight',
  // 'Northumberland',
  // 'Rutland',
  'Shropshire',
  'Wiltshire',
];
