name: Deploy Firebase Hosting (PR)

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: firebase-hosting-pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npm run build

      - name: Deploy Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENGLISHCOUNTIES }}
          channelId: pr-${{ github.event.number }}
          projectId: englishcounties
